{
 "title": "Bookservice",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success Rate - Resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats_counts.bookservice.cluster.bookservice_HIGH.upstream_rq_200, '2xx ')"
    },
    {
     "target": "alias(stats_counts.bookservice.cluster.bookservice_HIGH.upstream_rq_503, '503 ')"
    },
    {
     "target": "alias(stats_counts.bookservice.cluster.bookservice_HIGH.upstream_rq_504, '504 ')"
    },
    {
     "target": "alias(stats_counts.bookservice.cluster.bookservice_HIGH.upstream_rq_500, '500 ')"
    }
   ]
  },
  {
   "title": "Response Time - resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.bookservice.cluster.bookservice_HIGH.upstream_rq_time.mean, 'avg')"
    },
    {
     "target": "alias(stats.timers.bookservice.cluster.bookservice_HIGH.upstream_rq_time.lower, 'min')"
    },
    {
     "target": "alias(stats.timers.bookservice.cluster.bookservice_HIGH.upstream_rq_time.upper, 'max')"
    }
   ]
  },
  {
   "title": "Queue Length - Resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.bookservice.cluster.bookservice_HIGH.upstream_rq_pending_active"
    }
   ]
  },
  {
   "title": "Active Requests - resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.bookservice.cluster.bookservice_HIGH.upstream_rq_active"
    }
   ]
  },
  {
   "title": "Success Rate - no Resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats_counts.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_2xx, '2xx ')"
    },
    {
     "target": "alias(stats_counts.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_503, '503 ')"
    },
    {
     "target": "alias(stats_counts.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_504, '504 ')"
    },
    {
     "target": "alias(stats_counts.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_500, '500 ')"
    }
   ]
  },
  {
   "title": "Response Time - resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_time.mean, 'avg')"
    },
    {
     "target": "alias(stats.timers.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_time.lower, 'min')"
    },
    {
     "target": "alias(stats.timers.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_time.upper, 'max')"
    }
   ]
  },
  {
   "title": "Queue Length - no Resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_pending_active"
    }
   ]
  },
  {
   "title": "Active Requests - no Resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.bookservice-noresiliency.cluster.local_bookservice.upstream_rq_active"
    }
   ]
  },
  {
   "title": "Circuit breakers - resiliency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.bookservice.cluster.bookservice_HIGH.circuit_breakers.high.cx_open, 'cx')"
    },
    {
     "target": "alias(stats.gauges.bookservice.cluster.bookservice_HIGH.circuit_breakers.high.rq_pending_open, 'queue')"
    }
   ]
  }
 ]
}