{
 "title": "Success Rates",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success Rate %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (bookservice_noresiliency_cluster_local_bookservice_internal_upstream_rq_2xx [10s])  ",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate (bookservice_noresiliency_cluster_local_bookservice_internal_upstream_rq_5xx [10s]) ",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response time seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bookservice_noresiliency_cluster_local_bookservice_internal_upstream_rq_time{quantile=\"0.99\"}[15s])) * 1000",
     "legendFormat": "PMINC"
    },
    {
     "expr": "bookservice_noresiliency_cluster_local_bookservice_internal_upstream_rq_time{quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Saturation - Total RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bookservice_noresiliency_cluster_local_bookservice_upstream_cx_total[10s])"
    }
   ]
  },
  {
   "title": "CPU Usage in Cluster (Avg 30s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"bookservice-noresiliency.*$\"}[30s])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "CPU over limits (30s Avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kube_metrics_server_pods_cpu{pod_container_name=\"bookservice\",pod_name=~\"bookservice-noresiliency.*$\",pod_namespace=\"default\"}[30s])  /  10000 )  / (sum(container_spec_cpu_quota{pod_name=~\"bookservice-noresiliency.*$\",container_name=\"bookservice\"} / container_spec_cpu_period{pod_name=~\"bookservice-noresiliency.*$\",container_name=\"bookservice\"}) * 1000 )",
     "legendFormat": "usage"
    },
    {
     "expr": "(sum(container_spec_cpu_quota{pod_name=~\"bookservice-noresiliency.*$\",container_name=\"bookservice\"} / container_spec_cpu_period{pod_name=~\"bookservice-noresiliency.*$\",container_name=\"bookservice\"}) * 1000 )",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "BookService CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(avg_over_time(kube_metrics_server_pods_cpu{pod_container_name=\"bookservice\",pod_name=~\"bookservice-noresiliency.*$\",pod_namespace=\"default\"}[10s])  /  10000 )  / (sum(container_spec_cpu_quota{pod_name=~\"bookservice-noresiliency.*$\",container_name=\"bookservice\"} / container_spec_cpu_period{pod_name=~\"bookservice-noresiliency.*$\",container_name=\"bookservice\"}) * 1000 )",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "BookService Sidecar CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "sum(avg_over_time(kube_metrics_server_pods_cpu{pod_container_name=\"bookservice-sidecar\",pod_name=~\"bookservice-noresiliency.*$\",pod_namespace=\"default\"}[10s])  /  10000 )  / (sum(container_spec_cpu_quota{pod_name=~\"bookservice-noresiliency.*$\",container_name=\"bookservice\"} / container_spec_cpu_period{pod_name=~\"bookservice-noresiliency.*$\",container_name=\"bookservice\"}) * 1000 )",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"bookservice-noresiliency\",namespace=\"default\"}",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"bookservice-noresiliency\",namespace=\"default\"}",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}