{
 "title": "BookInfo Board",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Success Rate - Resiliency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"bookservice\",envoy_response_code_class=\"2\",job=\"bookinfo-spa\"}[10s])",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"bookservice\",envoy_response_code_class=\"5\",job=\"bookinfo-spa\"}[10s])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response time seconds - resiliency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa\"}[10s]) / rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa\"}[10s]) / 1000",
     "legendFormat": "AVG Downstream"
    },
    {
     "expr": "rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice\"}[10s]) / rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice\"}[10s]) / 1000",
     "legendFormat": "AVG Upstream"
    }
   ]
  },
  {
   "title": "Saturation - Total RPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa\"}[10s])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Active Requests - Resiliency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa\"}",
     "legendFormat": "Downstream"
    },
    {
     "expr": "envoy_cluster_upstream_rq_active{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice\"}",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "CPU Usage - Resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"bookservice\",pod_name=~\"bookservice-res.*\"}[40s]) / ignoring(cpu) (container_spec_cpu_quota{container_name=\"bookservice\",pod_name=~\"bookservice-res.*\"}/container_spec_cpu_period{container_name=\"bookservice\",pod_name=~\"bookservice-res.*\"}) * 100",
     "legendFormat": "BookService"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"bookservice-sidecar\",pod_name=~\"bookservice-res.*\"}[40s]) / ignoring(cpu) (container_spec_cpu_quota{container_name=\"bookservice-sidecar\",pod_name=~\"bookservice-res.*\"}/container_spec_cpu_period{container_name=\"bookservice-sidecar\",pod_name=~\"bookservice-res.*\"}) * 100",
     "legendFormat": "BookService Sidecar"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"bookinfo-spa\",pod_name=~\"bookinfo-spa-res.*\"}[40s]) / ignoring(cpu) (container_spec_cpu_quota{container_name=\"bookinfo-spa\",pod_name=~\"bookinfo-spa-res.*\"}/container_spec_cpu_period{container_name=\"bookinfo-spa\",pod_name=~\"bookinfo-spa-res.*\"}) * 100",
     "legendFormat": "BookInfo Sidecar"
    }
   ]
  },
  {
   "title": "Queueing - Resiliency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa\"}",
     "legendFormat": "Downstream"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice\"}",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "Success Rate - NO Resiliency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"bookservice\",envoy_response_code_class=\"2\",job=\"bookinfo-spa-noresiliency\"}[10s])\t",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"bookservice\",envoy_response_code_class=\"5\",job=\"bookinfo-spa-noresiliency\"}[10s])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response time seconds - NO resiliency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_time_sum{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa-noresiliency\"}[10s]) / rate(envoy_cluster_upstream_rq_time_count{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa-noresiliency\"}[10s]) / 1000",
     "legendFormat": "AVG Downstream"
    },
    {
     "expr": "rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice-noresiliency\"}[10s]) / rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice-noresiliency\"}[10s]) / 1000",
     "legendFormat": "AVG Upstream"
    }
   ]
  },
  {
   "title": "Saturation - Total RPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa-noresiliency\"}[10s])"
    }
   ]
  },
  {
   "title": "Active Requests - NO Resiliency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa-noresiliency\"}",
     "legendFormat": "Downstream"
    },
    {
     "expr": "envoy_cluster_upstream_rq_active{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice-noresiliency\"}",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "CPU Usage - NO Resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"bookservice\",pod_name=~\"bookservice-nores.*\"}[40s]) / ignoring(cpu) (container_spec_cpu_quota{container_name=\"bookservice\",pod_name=~\"bookservice-nores+.*\"}/container_spec_cpu_period{container_name=\"bookservice\",pod_name=~\"bookservice-nores.*\"}) * 100",
     "legendFormat": "BookService"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"bookservice-sidecar\",pod_name=~\"bookservice-nores.*\"}[40s]) / ignoring(cpu) (container_spec_cpu_quota{container_name=\"bookservice-sidecar\",pod_name=~\"bookservice-nores+.*\"}/container_spec_cpu_period{container_name=\"bookservice-sidecar\",pod_name=~\"bookservice-nores.*\"}) * 100",
     "legendFormat": "BookService Sidecar"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"bookinfo-spa-noresiliency\",pod_name=~\"bookinfo-spa-noresiliency.*\"}[40s]) / ignoring(cpu) (container_spec_cpu_quota{container_name=\"bookinfo-spa-noresiliency\",pod_name=~\"bookinfo-spa-noresiliency.*\"}/container_spec_cpu_period{container_name=\"bookinfo-spa-noresiliency\",pod_name=~\"bookinfo-spa-noresiliency.*\"}) * 100",
     "legendFormat": "BookInfo Sidecar"
    }
   ]
  },
  {
   "title": "Queueing - No Resiliency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa-noresiliency\"}",
     "legendFormat": "Downstream"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice-noresiliency\"}",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "Overflows - Resiliency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa\"}[10s])",
     "legendFormat": "Downstream Pending"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_retry_overflow{envoy_cluster_name=\"bookservice\",group=\"services\",job=\"bookinfo-spa\"}[10s])",
     "legendFormat": "Downstream Retry"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=\"local_bookservice\",group=\"services\",job=\"bookservice\"}[10s])",
     "legendFormat": "Upstream Pending"
    }
   ]
  }
 ]
}