apiVersion: v1
kind: Service
metadata: 
  annotations: 
    prometheus.io/scrape: "true"
  name: prometheus
  labels:
    name: prometheus
spec:
  type: NodePort
  selector: 
    app: prometheus-server 
  ports: 
    - name: prometheus 
      port: 8080
      nodePort: 30100
      targetPort: prometheus